// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                         int32
	TelegramID                 int64
	IsBlocked                  bool
	IsSubscribedToBroadcasting bool
	CreatedAt                  pgtype.Timestamp
	UpdatedAt                  pgtype.Timestamp
}
